Vastly improved gt-scan script with better nmap commands.

diff --git a/scripts/gt-scan b/scripts/gt-scan
--- a/scripts/gt-scan
+++ b/scripts/gt-scan
@@ -1,8 +1,37 @@
 #!/usr/bin/env bash
 # nmap network scanner
-# Version 4.5
-# Gianluca Truda, 10 March 2017
+# Version 5.0
 
-MYIP="`ipconfig getifaddr en0`"
-echo "My IP: "$MYIP
-nmap -sP -A $MYIP/24
+# Ensure nmap is installed
+if ! command -v nmap &> /dev/null; then
+    echo "ERROR: nmap is not installed"
+fi
+
+if [[ -n "$1" && $1 != "-A" ]]; then
+	echo "Unrecognised argument."
+	echo -e "Usage: $0 [-A]\n"
+	exit 1
+fi
+
+# Retrieve local IP address
+MYIP=$(ipconfig getifaddr en0)
+echo "My IP: $MYIP"
+
+# Assuming a typical subnet mask of 255.255.255.0
+NETBASE=$(echo $MYIP | sed 's/\.[0-9]*$/.0/')
+echo "Network base: $NETBASE"
+
+echo -e "\nPerforming quick ping scan of $NETBASE/24\n"
+(set -x; nmap -sn -R -T4 $NETBASE/24)
+
+echo -e "\n----------\n"
+
+echo -e "\nPerforming aggressive advanced scans with OS Detection.\nWARNING: You might get in trouble!\nSudo required.\n"
+if [[ -n "$1" && $1 == "-A" ]]; then
+	# -A: Enable OS detection, version detection, script scanning, and traceroute
+	(set -x; sudo nmap -R -A -O -T5 $NETBASE/24)
+	exit 1
+fi
+
+(set -x; sudo nmap -R -O -T5 $NETBASE/24)
+exit 1
