Enhance gt-synchdd Backup Script
Updated the gt-synchdd script to version 2.0, improving its functionality by adding logging capabilities and more robust error handling. Introduced a LOGDIR to store logs, where log files will be generated with a timestamp. Added a configurable list of subdirectories to sync, and implemented a backup feature for deleted files. Enhanced the script's rsync command with additional options for better file synchronization and exclusion of unnecessary files. This update makes the backup process more flexible and informative, especially for monitoring and debugging.

diff --git a/scripts/gt-synchdd b/scripts/gt-synchdd
--- a/scripts/gt-synchdd
+++ b/scripts/gt-synchdd
@@ -1,19 +1,54 @@
 #!/usr/bin/env bash
+# Version 2.0
 
-# source ~/.config/.extra # Get drive paths
+if ! [[ -n $LOGDIR ]]; then
+	LOGDIR="$HOME/3-Resources/Logs"
+	echo "LOGDIR not set. Creating at '$LOGDIR'"
+fi
+mkdir -p "$LOGDIR"
+LOGFILE="$LOGDIR/$(date +%Y-%m-%d_%H-%M-%S)_gt-synchdd.log"
+SUBDIRS_TO_SYNC=(
+	"0-Inbox" \
+	"1-Projects" \
+	"2-Areas" \
+	"3-Resources" \
+	"4-Archives" \
+)
+
+# TODO DEBUGGING...
+# TEST_PATH_01="$HOME/Desktop/test01"
+# TEST_PATH_02="$HOME/Desktop/test02"
+# for DRIVE in $TEST_PATH_01 $TEST_PATH_02; do
 for DRIVE in $BACKUP_HDD_01 $BACKUP_HDD_02; do
 	if ! [[ -n $DRIVE ]]; then
-		echo "Backup drives not properly specified in ~/.config/.extra"
-		exit 0
+		echo "Backup drives not properly specified. Check ~/.config/.extra"
+		exit 1 # Exit code 1 for error
 	fi
 	if ! [[ -e "$DRIVE" && -d "$DRIVE" ]]; then
-		echo "$DRIVE not found, skipping."
+		echo "\n$DRIVE not found, skipping.\n"
 		continue
 	fi
-	echo -e "\nSyncing '$DRIVE'...\n"
-	(set -x; rsync -avh --exclude '.DS_Store' $HOME/1-Projects/ "$DRIVE"/1-Projects/)
-	(set -x; rsync -avh --exclude '.DS_Store' $HOME/2-Areas/ "$DRIVE"/2-Areas/)
-	(set -x; rsync -avh --exclude '.DS_Store' $HOME/3-Resources/ "$DRIVE"/3-Resources/)
-	(set -x; rsync -avh --exclude '.DS_Store' $HOME/4-Archives/ "$DRIVE"/4-Archives/)
+	echo -e "\n\nSyncing '$DRIVE'...\n"
+	for SUBDIR in "${SUBDIRS_TO_SYNC[@]}"; do
+		(set -x; rsync -avh \
+			--backup \
+			--backup-dir="$DRIVE/Deleted/$(date +%Y-%m-%d_%H-%M-%S)" \
+			--delete-before \
+			--stats \
+			--progress \
+			--log-file="$LOGFILE" \
+			--exclude='.DS_Store' \
+			--exclude='.DocumentRevisions-V100' \
+			--exclude='.Spotlight-V100' \
+			--exclude='.TemporaryItems' \
+			--exclude='.Trashes' \
+			--exclude='._*' \
+			--exclude='.fseventsd' \
+			--exclude='.timemachine' \
+			"$HOME/$SUBDIR/" "$DRIVE/$SUBDIR/" \
+		)
+	done
 	echo -e "\nFinished syncing to '$DRIVE'\n"
 done
+
+echo -e "\nLogs written to '$LOGFILE'\n"
